name: pre-commit
on:
  push:
    branches: [ main ] # cambia "main" si tu rama por defecto es otra
  pull_request:
  workflow_dispatch:


permissions:
  contents: read

concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Cache pre-commit env
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-precommit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: ${{ runner.os }}-precommit-
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --show-diff-on-failure
